#![feature(abi_msp430_interrupt)]
#![doc = "Peripheral access API for MSP430F149 microcontrollers (generated using svd2rust v0.37.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
#[allow(unused_imports)]
use generic::*;
#[doc = "Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
extern "msp430-interrupt" {
    fn PORT2();
    fn USART1TX();
    fn USART1RX();
    fn PORT1();
    fn TIMERA1();
    fn TIMERA0();
    fn ADC12();
    fn USART0TX();
    fn USART0RX();
    fn WDT();
    fn COMPARATORA();
    fn TIMERB1();
    fn TIMERB0();
    fn NMI();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "msp430-interrupt" fn(),
    _reserved: u16,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
#[used]
pub static __INTERRUPTS: [Vector; 15] = [
    Vector { _reserved: 0 },
    Vector { _handler: PORT2 },
    Vector { _handler: USART1TX },
    Vector { _handler: USART1RX },
    Vector { _handler: PORT1 },
    Vector { _handler: TIMERA1 },
    Vector { _handler: TIMERA0 },
    Vector { _handler: ADC12 },
    Vector { _handler: USART0TX },
    Vector { _handler: USART0RX },
    Vector { _handler: WDT },
    Vector { _handler: COMPARATORA },
    Vector { _handler: TIMERB1 },
    Vector { _handler: TIMERB0 },
    Vector { _handler: NMI },
];
#[doc = r"Enumeration of all the interrupts. This enum is seldom used in application or library crates. It is present primarily for documenting the device's implemented interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "1 - 0xFFE2 Port 2"]
    PORT2 = 1,
    #[doc = "2 - 0xFFE4 USART 1 Transmit"]
    USART1TX = 2,
    #[doc = "3 - 0xFFE6 USART 1 Receive"]
    USART1RX = 3,
    #[doc = "4 - 0xFFE8 Port 1"]
    PORT1 = 4,
    #[doc = "5 - 0xFFEA Timer A CC1-2, TA"]
    TIMERA1 = 5,
    #[doc = "6 - 0xFFEC Timer A CC0"]
    TIMERA0 = 6,
    #[doc = "7 - 0xFFEE ADC"]
    ADC12 = 7,
    #[doc = "8 - 0xFFF0 USART 0 Transmit"]
    USART0TX = 8,
    #[doc = "9 - 0xFFF2 USART 0 Receive"]
    USART0RX = 9,
    #[doc = "10 - 0xFFF4 Watchdog Timer"]
    WDT = 10,
    #[doc = "11 - 0xFFF6 Comparator A"]
    COMPARATORA = 11,
    #[doc = "12 - 0xFFF8 Timer B CC1-6, TB"]
    TIMERB1 = 12,
    #[doc = "13 - 0xFFFA Timer B CC0"]
    TIMERB0 = 13,
    #[doc = "14 - 0xFFFC Non-maskable"]
    NMI = 14,
}
#[doc = "Special Function"]
pub type SpecialFunction = crate::Periph<special_function::RegisterBlock, 0>;
impl core::fmt::Debug for SpecialFunction {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SpecialFunction").finish()
    }
}
#[doc = "Special Function"]
pub mod special_function;
#[doc = "Port 3/4"]
pub type Port3_4 = crate::Periph<port_3_4::RegisterBlock, 0x18>;
impl core::fmt::Debug for Port3_4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Port3_4").finish()
    }
}
#[doc = "Port 3/4"]
pub mod port_3_4;
#[doc = "Port 1/2"]
pub type Port1_2 = crate::Periph<port_1_2::RegisterBlock, 0x20>;
impl core::fmt::Debug for Port1_2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Port1_2").finish()
    }
}
#[doc = "Port 1/2"]
pub mod port_1_2;
#[doc = "Port 5/6"]
pub type Port5_6 = crate::Periph<port_5_6::RegisterBlock, 0x30>;
impl core::fmt::Debug for Port5_6 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Port5_6").finish()
    }
}
#[doc = "Port 5/6"]
pub mod port_5_6;
#[doc = "System Clock"]
pub type SystemClock = crate::Periph<system_clock::RegisterBlock, 0x56>;
impl core::fmt::Debug for SystemClock {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SystemClock").finish()
    }
}
#[doc = "System Clock"]
pub mod system_clock;
#[doc = "Comparator A"]
pub type ComparatorA = crate::Periph<comparator_a::RegisterBlock, 0x58>;
impl core::fmt::Debug for ComparatorA {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("ComparatorA").finish()
    }
}
#[doc = "Comparator A"]
pub mod comparator_a;
#[doc = "USART 0 UART/SPI Mode"]
pub type Usart0UartSpiMode = crate::Periph<usart_0_uart_spi_mode::RegisterBlock, 0x70>;
impl core::fmt::Debug for Usart0UartSpiMode {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart0UartSpiMode").finish()
    }
}
#[doc = "USART 0 UART/SPI Mode"]
pub mod usart_0_uart_spi_mode;
#[doc = "USART 1"]
pub type Usart1 = crate::Periph<usart_1::RegisterBlock, 0x78>;
impl core::fmt::Debug for Usart1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart1").finish()
    }
}
#[doc = "USART 1"]
pub mod usart_1;
#[doc = "ADC12"]
pub type Adc12 = crate::Periph<adc12::RegisterBlock, 0x80>;
impl core::fmt::Debug for Adc12 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Adc12").finish()
    }
}
#[doc = "ADC12"]
pub mod adc12;
#[doc = "Timer B7"]
pub type TimerB7 = crate::Periph<timer_b7::RegisterBlock, 0x011e>;
impl core::fmt::Debug for TimerB7 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TimerB7").finish()
    }
}
#[doc = "Timer B7"]
pub mod timer_b7;
#[doc = "Watchdog Timer"]
pub type WatchdogTimer = crate::Periph<watchdog_timer::RegisterBlock, 0x0120>;
impl core::fmt::Debug for WatchdogTimer {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("WatchdogTimer").finish()
    }
}
#[doc = "Watchdog Timer"]
pub mod watchdog_timer;
#[doc = "Flash"]
pub type Flash = crate::Periph<flash::RegisterBlock, 0x0128>;
impl core::fmt::Debug for Flash {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Flash").finish()
    }
}
#[doc = "Flash"]
pub mod flash;
#[doc = "Timer A3"]
pub type TimerA3 = crate::Periph<timer_a3::RegisterBlock, 0x012e>;
impl core::fmt::Debug for TimerA3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TimerA3").finish()
    }
}
#[doc = "Timer A3"]
pub mod timer_a3;
#[doc = "Multiplier"]
pub type Multiplier = crate::Periph<multiplier::RegisterBlock, 0x0130>;
impl core::fmt::Debug for Multiplier {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Multiplier").finish()
    }
}
#[doc = "Multiplier"]
pub mod multiplier;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "SPECIAL_FUNCTION"]
    pub special_function: SpecialFunction,
    #[doc = "PORT_3_4"]
    pub port_3_4: Port3_4,
    #[doc = "PORT_1_2"]
    pub port_1_2: Port1_2,
    #[doc = "PORT_5_6"]
    pub port_5_6: Port5_6,
    #[doc = "SYSTEM_CLOCK"]
    pub system_clock: SystemClock,
    #[doc = "COMPARATOR_A"]
    pub comparator_a: ComparatorA,
    #[doc = "USART_0_UART_SPI_MODE"]
    pub usart_0_uart_spi_mode: Usart0UartSpiMode,
    #[doc = "USART_1"]
    pub usart_1: Usart1,
    #[doc = "ADC12"]
    pub adc12: Adc12,
    #[doc = "TIMER_B7"]
    pub timer_b7: TimerB7,
    #[doc = "WATCHDOG_TIMER"]
    pub watchdog_timer: WatchdogTimer,
    #[doc = "FLASH"]
    pub flash: Flash,
    #[doc = "TIMER_A3"]
    pub timer_a3: TimerA3,
    #[doc = "MULTIPLIER"]
    pub multiplier: Multiplier,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            special_function: SpecialFunction::steal(),
            port_3_4: Port3_4::steal(),
            port_1_2: Port1_2::steal(),
            port_5_6: Port5_6::steal(),
            system_clock: SystemClock::steal(),
            comparator_a: ComparatorA::steal(),
            usart_0_uart_spi_mode: Usart0UartSpiMode::steal(),
            usart_1: Usart1::steal(),
            adc12: Adc12::steal(),
            timer_b7: TimerB7::steal(),
            watchdog_timer: WatchdogTimer::steal(),
            flash: Flash::steal(),
            timer_a3: TimerA3::steal(),
            multiplier: Multiplier::steal(),
        }
    }
}
