[package]
edition = "2024"
name = "embassy-msp430fr2355-examples"
version = "0.1.0"
license = "MIT OR Apache-2.0"

[dependencies]
embassy-executor = { version = "0.10.0", path = "../../embassy-executor", features = ["platform-msp430", "executor-thread"] }
embassy-time = { version = "0.5.1", path = "../../embassy-time", features = ["tick-hz-32_768"] }
embassy-time-driver = { version = "0.2.2", path = "../../embassy-time-driver" }
embassy-time-queue-utils = { version = "0.3.0", path = "../../embassy-time-queue-utils" }
embassy-sync = { version = "0.8.0", path = "../../embassy-sync" }
embassy-futures = { version = "0.1.2", path = "../../embassy-futures" }

msp430 = { version = "0.4.1", features = ["critical-section-single-core"] }
msp430-rt = "0.4.1"
msp430fr2355 = { version = "0.6.1", features = ["rt", "critical-section"] }
critical-section = "1.1"

[profile.dev]
codegen-units = 1
debug = 2
opt-level = "s"     # MSP430FR2355 only has 32 kB of FRAM, never build this unoptimized.
overflow-checks = false

[profile.release]
codegen-units = 1
debug = 2
lto = true
opt-level = "z"
overflow-checks = false
