#![feature(abi_msp430_interrupt)]
#![doc = "Peripheral access API for MSP430F2618 microcontrollers (generated using svd2rust v0.37.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
#[allow(unused_imports)]
use generic::*;
#[doc = "Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
extern "msp430-interrupt" {
    fn RESERVED0();
    fn RESERVED1();
    fn RESERVED2();
    fn RESERVED3();
    fn RESERVED4();
    fn RESERVED5();
    fn RESERVED6();
    fn RESERVED7();
    fn RESERVED8();
    fn RESERVED9();
    fn RESERVED10();
    fn RESERVED11();
    fn RESERVED12();
    fn RESERVED13();
    fn DAC12();
    fn DMA();
    fn USCIAB1TX();
    fn USCIAB1RX();
    fn PORT1();
    fn PORT2();
    fn RESERVED20();
    fn ADC12();
    fn USCIAB0TX();
    fn USCIAB0RX();
    fn TIMERA1();
    fn TIMERA0();
    fn WDT();
    fn COMPARATORA();
    fn TIMERB1();
    fn TIMERB0();
    fn NMI();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "msp430-interrupt" fn(),
    _reserved: u16,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
#[used]
pub static __INTERRUPTS: [Vector; 31] = [
    Vector { _handler: RESERVED0 },
    Vector { _handler: RESERVED1 },
    Vector { _handler: RESERVED2 },
    Vector { _handler: RESERVED3 },
    Vector { _handler: RESERVED4 },
    Vector { _handler: RESERVED5 },
    Vector { _handler: RESERVED6 },
    Vector { _handler: RESERVED7 },
    Vector { _handler: RESERVED8 },
    Vector { _handler: RESERVED9 },
    Vector { _handler: RESERVED10 },
    Vector { _handler: RESERVED11 },
    Vector { _handler: RESERVED12 },
    Vector { _handler: RESERVED13 },
    Vector { _handler: DAC12 },
    Vector { _handler: DMA },
    Vector { _handler: USCIAB1TX },
    Vector { _handler: USCIAB1RX },
    Vector { _handler: PORT1 },
    Vector { _handler: PORT2 },
    Vector { _handler: RESERVED20 },
    Vector { _handler: ADC12 },
    Vector { _handler: USCIAB0TX },
    Vector { _handler: USCIAB0RX },
    Vector { _handler: TIMERA1 },
    Vector { _handler: TIMERA0 },
    Vector { _handler: WDT },
    Vector { _handler: COMPARATORA },
    Vector { _handler: TIMERB1 },
    Vector { _handler: TIMERB0 },
    Vector { _handler: NMI },
];
#[doc = r"Enumeration of all the interrupts. This enum is seldom used in application or library crates. It is present primarily for documenting the device's implemented interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "0 - 0xFFC0 Reserved Int. Vector 0"]
    RESERVED0 = 0,
    #[doc = "1 - 0xFFC2 Reserved Int. Vector 1"]
    RESERVED1 = 1,
    #[doc = "2 - 0xFFC4 Reserved Int. Vector 2"]
    RESERVED2 = 2,
    #[doc = "3 - 0xFFC6 Reserved Int. Vector 3"]
    RESERVED3 = 3,
    #[doc = "4 - 0xFFC8 Reserved Int. Vector 4"]
    RESERVED4 = 4,
    #[doc = "5 - 0xFFCA Reserved Int. Vector 5"]
    RESERVED5 = 5,
    #[doc = "6 - 0xFFCC Reserved Int. Vector 6"]
    RESERVED6 = 6,
    #[doc = "7 - 0xFFCE Reserved Int. Vector 7"]
    RESERVED7 = 7,
    #[doc = "8 - 0xFFD0 Reserved Int. Vector 8"]
    RESERVED8 = 8,
    #[doc = "9 - 0xFFD2 Reserved Int. Vector 9"]
    RESERVED9 = 9,
    #[doc = "10 - 0xFFD4 Reserved Int. Vector 10"]
    RESERVED10 = 10,
    #[doc = "11 - 0xFFD6 Reserved Int. Vector 11"]
    RESERVED11 = 11,
    #[doc = "12 - 0xFFD8 Reserved Int. Vector 12"]
    RESERVED12 = 12,
    #[doc = "13 - 0xFFDA Reserved Int. Vector 13"]
    RESERVED13 = 13,
    #[doc = "14 - 0xFFDC DAC12"]
    DAC12 = 14,
    #[doc = "15 - 0xFFDE DMA"]
    DMA = 15,
    #[doc = "16 - 0xFFE0 USCI A1/B1 Transmit"]
    USCIAB1TX = 16,
    #[doc = "17 - 0xFFE2 USCI A1/B1 Receive"]
    USCIAB1RX = 17,
    #[doc = "18 - 0xFFE4 Port 1"]
    PORT1 = 18,
    #[doc = "19 - 0xFFE6 Port 2"]
    PORT2 = 19,
    #[doc = "20 - 0xFFE8 Reserved Int. Vector 20"]
    RESERVED20 = 20,
    #[doc = "21 - 0xFFEA ADC"]
    ADC12 = 21,
    #[doc = "22 - 0xFFEC USCI A0/B0 Transmit"]
    USCIAB0TX = 22,
    #[doc = "23 - 0xFFEE USCI A0/B0 Receive"]
    USCIAB0RX = 23,
    #[doc = "24 - 0xFFF0 Timer A CC1-2, TA"]
    TIMERA1 = 24,
    #[doc = "25 - 0xFFF2 Timer A CC0"]
    TIMERA0 = 25,
    #[doc = "26 - 0xFFF4 Watchdog Timer"]
    WDT = 26,
    #[doc = "27 - 0xFFF6 Comparator A"]
    COMPARATORA = 27,
    #[doc = "28 - 0xFFF8 Timer B CC1-6, TB"]
    TIMERB1 = 28,
    #[doc = "29 - 0xFFFA Timer B CC0"]
    TIMERB0 = 29,
    #[doc = "30 - 0xFFFC Non-maskable"]
    NMI = 30,
}
#[doc = "Special Function"]
pub type SpecialFunction = crate::Periph<special_function::RegisterBlock, 0>;
impl core::fmt::Debug for SpecialFunction {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SpecialFunction").finish()
    }
}
#[doc = "Special Function"]
pub mod special_function;
#[doc = "Port 3/4"]
pub type Port3_4 = crate::Periph<port_3_4::RegisterBlock, 0x10>;
impl core::fmt::Debug for Port3_4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Port3_4").finish()
    }
}
#[doc = "Port 3/4"]
pub mod port_3_4;
#[doc = "Port 5/6"]
pub type Port5_6 = crate::Periph<port_5_6::RegisterBlock, 0x12>;
impl core::fmt::Debug for Port5_6 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Port5_6").finish()
    }
}
#[doc = "Port 5/6"]
pub mod port_5_6;
#[doc = "Port 7/8"]
pub type Port7_8 = crate::Periph<port_7_8::RegisterBlock, 0x14>;
impl core::fmt::Debug for Port7_8 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Port7_8").finish()
    }
}
#[doc = "Port 7/8"]
pub mod port_7_8;
#[doc = "Port 1/2"]
pub type Port1_2 = crate::Periph<port_1_2::RegisterBlock, 0x20>;
impl core::fmt::Debug for Port1_2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Port1_2").finish()
    }
}
#[doc = "Port 1/2"]
pub mod port_1_2;
#[doc = "System Clock"]
pub type SystemClock = crate::Periph<system_clock::RegisterBlock, 0x52>;
impl core::fmt::Debug for SystemClock {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SystemClock").finish()
    }
}
#[doc = "System Clock"]
pub mod system_clock;
#[doc = "Supply Voltage Supervisor"]
pub type SupplyVoltageSupervisor = crate::Periph<supply_voltage_supervisor::RegisterBlock, 0x54>;
impl core::fmt::Debug for SupplyVoltageSupervisor {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SupplyVoltageSupervisor").finish()
    }
}
#[doc = "Supply Voltage Supervisor"]
pub mod supply_voltage_supervisor;
#[doc = "Comparator A"]
pub type ComparatorA = crate::Periph<comparator_a::RegisterBlock, 0x58>;
impl core::fmt::Debug for ComparatorA {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("ComparatorA").finish()
    }
}
#[doc = "Comparator A"]
pub mod comparator_a;
#[doc = "USCI_A0 UART Mode"]
pub type UsciA0UartMode = crate::Periph<usci_a0_uart_mode::RegisterBlock, 0x5c>;
impl core::fmt::Debug for UsciA0UartMode {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UsciA0UartMode").finish()
    }
}
#[doc = "USCI_A0 UART Mode"]
pub mod usci_a0_uart_mode;
#[doc = "USCI_A0 SPI Mode"]
pub type UsciA0SpiMode = crate::Periph<usci_a0_spi_mode::RegisterBlock, 0x60>;
impl core::fmt::Debug for UsciA0SpiMode {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UsciA0SpiMode").finish()
    }
}
#[doc = "USCI_A0 SPI Mode"]
pub mod usci_a0_spi_mode;
#[doc = "USCI_B0 I2C Mode"]
pub type UsciB0I2cMode = crate::Periph<usci_b0_i2c_mode::RegisterBlock, 0x68>;
impl core::fmt::Debug for UsciB0I2cMode {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UsciB0I2cMode").finish()
    }
}
#[doc = "USCI_B0 I2C Mode"]
pub mod usci_b0_i2c_mode;
#[doc = "USCI_B0 SPI Mode"]
pub type UsciB0SpiMode = crate::Periph<usci_b0_spi_mode::RegisterBlock, 0x68>;
impl core::fmt::Debug for UsciB0SpiMode {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UsciB0SpiMode").finish()
    }
}
#[doc = "USCI_B0 SPI Mode"]
pub mod usci_b0_spi_mode;
#[doc = "ADC12"]
pub type Adc12 = crate::Periph<adc12::RegisterBlock, 0x80>;
impl core::fmt::Debug for Adc12 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Adc12").finish()
    }
}
#[doc = "ADC12"]
pub mod adc12;
#[doc = "USCI_A1 UART Mode"]
pub type UsciA1UartMode = crate::Periph<usci_a1_uart_mode::RegisterBlock, 0xcc>;
impl core::fmt::Debug for UsciA1UartMode {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UsciA1UartMode").finish()
    }
}
#[doc = "USCI_A1 UART Mode"]
pub mod usci_a1_uart_mode;
#[doc = "USCI_A1 SPI Mode"]
pub type UsciA1SpiMode = crate::Periph<usci_a1_spi_mode::RegisterBlock, 0xd0>;
impl core::fmt::Debug for UsciA1SpiMode {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UsciA1SpiMode").finish()
    }
}
#[doc = "USCI_A1 SPI Mode"]
pub mod usci_a1_spi_mode;
#[doc = "USCI_B1 I2C Mode"]
pub type UsciB1I2cMode = crate::Periph<usci_b1_i2c_mode::RegisterBlock, 0xd8>;
impl core::fmt::Debug for UsciB1I2cMode {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UsciB1I2cMode").finish()
    }
}
#[doc = "USCI_B1 I2C Mode"]
pub mod usci_b1_i2c_mode;
#[doc = "USCI_B1 SPI Mode"]
pub type UsciB1SpiMode = crate::Periph<usci_b1_spi_mode::RegisterBlock, 0xd8>;
impl core::fmt::Debug for UsciB1SpiMode {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UsciB1SpiMode").finish()
    }
}
#[doc = "USCI_B1 SPI Mode"]
pub mod usci_b1_spi_mode;
#[doc = "TLV Calibration Data"]
pub type TlvCalibrationData = crate::Periph<tlv_calibration_data::RegisterBlock, 0x10c0>;
impl core::fmt::Debug for TlvCalibrationData {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TlvCalibrationData").finish()
    }
}
#[doc = "TLV Calibration Data"]
pub mod tlv_calibration_data;
#[doc = "Calibration Data"]
pub type CalibrationData = crate::Periph<calibration_data::RegisterBlock, 0x10f8>;
impl core::fmt::Debug for CalibrationData {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CalibrationData").finish()
    }
}
#[doc = "Calibration Data"]
pub mod calibration_data;
#[doc = "Timer B7"]
pub type TimerB7 = crate::Periph<timer_b7::RegisterBlock, 0x011e>;
impl core::fmt::Debug for TimerB7 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TimerB7").finish()
    }
}
#[doc = "Timer B7"]
pub mod timer_b7;
#[doc = "Watchdog Timer"]
pub type WatchdogTimer = crate::Periph<watchdog_timer::RegisterBlock, 0x0120>;
impl core::fmt::Debug for WatchdogTimer {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("WatchdogTimer").finish()
    }
}
#[doc = "Watchdog Timer"]
pub mod watchdog_timer;
#[doc = "DMA"]
pub type Dma = crate::Periph<dma::RegisterBlock, 0x0122>;
impl core::fmt::Debug for Dma {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dma").finish()
    }
}
#[doc = "DMA"]
pub mod dma;
#[doc = "Flash"]
pub type Flash = crate::Periph<flash::RegisterBlock, 0x0128>;
impl core::fmt::Debug for Flash {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Flash").finish()
    }
}
#[doc = "Flash"]
pub mod flash;
#[doc = "Timer A3"]
pub type TimerA3 = crate::Periph<timer_a3::RegisterBlock, 0x012e>;
impl core::fmt::Debug for TimerA3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TimerA3").finish()
    }
}
#[doc = "Timer A3"]
pub mod timer_a3;
#[doc = "Multiplier"]
pub type Multiplier = crate::Periph<multiplier::RegisterBlock, 0x0130>;
impl core::fmt::Debug for Multiplier {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Multiplier").finish()
    }
}
#[doc = "Multiplier"]
pub mod multiplier;
#[doc = "DAC12"]
pub type Dac12 = crate::Periph<dac12::RegisterBlock, 0x01c0>;
impl core::fmt::Debug for Dac12 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dac12").finish()
    }
}
#[doc = "DAC12"]
pub mod dac12;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "SPECIAL_FUNCTION"]
    pub special_function: SpecialFunction,
    #[doc = "PORT_3_4"]
    pub port_3_4: Port3_4,
    #[doc = "PORT_5_6"]
    pub port_5_6: Port5_6,
    #[doc = "PORT_7_8"]
    pub port_7_8: Port7_8,
    #[doc = "PORT_1_2"]
    pub port_1_2: Port1_2,
    #[doc = "SYSTEM_CLOCK"]
    pub system_clock: SystemClock,
    #[doc = "SUPPLY_VOLTAGE_SUPERVISOR"]
    pub supply_voltage_supervisor: SupplyVoltageSupervisor,
    #[doc = "COMPARATOR_A"]
    pub comparator_a: ComparatorA,
    #[doc = "USCI_A0_UART_MODE"]
    pub usci_a0_uart_mode: UsciA0UartMode,
    #[doc = "USCI_A0_SPI_MODE"]
    pub usci_a0_spi_mode: UsciA0SpiMode,
    #[doc = "USCI_B0_I2C_MODE"]
    pub usci_b0_i2c_mode: UsciB0I2cMode,
    #[doc = "USCI_B0_SPI_MODE"]
    pub usci_b0_spi_mode: UsciB0SpiMode,
    #[doc = "ADC12"]
    pub adc12: Adc12,
    #[doc = "USCI_A1_UART_MODE"]
    pub usci_a1_uart_mode: UsciA1UartMode,
    #[doc = "USCI_A1_SPI_MODE"]
    pub usci_a1_spi_mode: UsciA1SpiMode,
    #[doc = "USCI_B1_I2C_MODE"]
    pub usci_b1_i2c_mode: UsciB1I2cMode,
    #[doc = "USCI_B1_SPI_MODE"]
    pub usci_b1_spi_mode: UsciB1SpiMode,
    #[doc = "TLV_CALIBRATION_DATA"]
    pub tlv_calibration_data: TlvCalibrationData,
    #[doc = "CALIBRATION_DATA"]
    pub calibration_data: CalibrationData,
    #[doc = "TIMER_B7"]
    pub timer_b7: TimerB7,
    #[doc = "WATCHDOG_TIMER"]
    pub watchdog_timer: WatchdogTimer,
    #[doc = "DMA"]
    pub dma: Dma,
    #[doc = "FLASH"]
    pub flash: Flash,
    #[doc = "TIMER_A3"]
    pub timer_a3: TimerA3,
    #[doc = "MULTIPLIER"]
    pub multiplier: Multiplier,
    #[doc = "DAC12"]
    pub dac12: Dac12,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            special_function: SpecialFunction::steal(),
            port_3_4: Port3_4::steal(),
            port_5_6: Port5_6::steal(),
            port_7_8: Port7_8::steal(),
            port_1_2: Port1_2::steal(),
            system_clock: SystemClock::steal(),
            supply_voltage_supervisor: SupplyVoltageSupervisor::steal(),
            comparator_a: ComparatorA::steal(),
            usci_a0_uart_mode: UsciA0UartMode::steal(),
            usci_a0_spi_mode: UsciA0SpiMode::steal(),
            usci_b0_i2c_mode: UsciB0I2cMode::steal(),
            usci_b0_spi_mode: UsciB0SpiMode::steal(),
            adc12: Adc12::steal(),
            usci_a1_uart_mode: UsciA1UartMode::steal(),
            usci_a1_spi_mode: UsciA1SpiMode::steal(),
            usci_b1_i2c_mode: UsciB1I2cMode::steal(),
            usci_b1_spi_mode: UsciB1SpiMode::steal(),
            tlv_calibration_data: TlvCalibrationData::steal(),
            calibration_data: CalibrationData::steal(),
            timer_b7: TimerB7::steal(),
            watchdog_timer: WatchdogTimer::steal(),
            dma: Dma::steal(),
            flash: Flash::steal(),
            timer_a3: TimerA3::steal(),
            multiplier: Multiplier::steal(),
            dac12: Dac12::steal(),
        }
    }
}
